import { useState } from "react"
import { useNavigate } from "react-router-dom"
import { jobsAPI } from "../../api/index"
import toast from "react-hot-toast"
import { aiAPI } from "../../api/index"

const CreateJob = () => {

    const navigate = useNavigate()

    const [generatingDesc, setGeneratingDesc] = useState(false)
    const [loading, setLoading] = useState(false)
    const [form, setForm] = useState({
        title: "", description: "", department: "",
        location: "", jobType: "full-time",
        experienceRequired: 0, deadline: "",
        requirements: "", niceToHave: "",
        salary: { min: 0, max: 0, currency: "INR" }
    })

    const handleGenerateDesc = async () => {
        if (!form.title) return toast.error("Enter job title first")
        setGeneratingDesc(true)
        try {
            const res = await aiAPI.generateJobDesc({
                jobId: "placeholder",
                title: form.title,
                department: form.department
            })
            const result = res.data.result
            setForm(prev => ({
                ...prev,
                description: result.description,
                requirements: result.requirements.join(", "),
                niceToHave: result.niceToHave.join(", "),
                experienceRequired: result.experienceRequired
            }))
            toast.success("Job description generated by AI!")
        } catch (err) {
            toast.error("Failed to generate description")
        } finally {
            setGeneratingDesc(false)
        }
    }

    const handleChange = (e) => {
        const { name, value } = e.target
        if (name === "salaryMin") return setForm({ ...form, salary: { ...form.salary, min: value } })
        if (name === "salaryMax") return setForm({ ...form, salary: { ...form.salary, max: value } })
        setForm({ ...form, [name]: value })
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        if (!form.title || !form.description || !form.deadline) {
            return toast.error("Please fill required fields")
        }
        setLoading(true)
        try {
            const payload = {
                ...form,
                requirements: form.requirements.split(",").map(s => s.trim()).filter(Boolean),
                niceToHave: form.niceToHave.split(",").map(s => s.trim()).filter(Boolean),
            }
            await jobsAPI.create(payload)
            toast.success("Job created successfully!")
            navigate("/jobs")
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to create job")
        } finally {
            setLoading(false)
        }
    }

    const inputStyle = {
        width: "100%", padding: "12px 16px",
        border: "1.5px solid #e2e8f0", borderRadius: "12px",
        fontSize: "14px", outline: "none", boxSizing: "border-box",
        color: "#0f172a", background: "white"
    }

    const labelStyle = {
        display: "block", fontSize: "14px",
        fontWeight: "600", color: "#374151", marginBottom: "8px"
    }

    return (
        <div style={{ maxWidth: "800px" }}>
            <div style={{ marginBottom: "32px" }}>
                <button onClick={() => navigate("/jobs")} style={{
                    background: "none", border: "none", color: "#6366f1",
                    fontSize: "14px", cursor: "pointer", marginBottom: "16px",
                    padding: 0, fontWeight: "600"
                }}>← Back to Jobs</button>
                <h1 style={{ fontSize: "28px", fontWeight: "800", color: "#0f172a", marginBottom: "4px" }}>
                    Post New Job
                </h1>
                <p style={{ color: "#64748b" }}>Fill in the details to create a new job posting</p>
            </div>

            <form onSubmit={handleSubmit}>
                <div style={{ background: "white", borderRadius: "16px", padding: "32px", border: "1px solid #e2e8f0", marginBottom: "20px" }}>
                    <h2 style={{ fontSize: "16px", fontWeight: "700", color: "#0f172a", marginBottom: "24px" }}>
                        Basic Information
                    </h2>

                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
                        <div style={{ gridColumn: "1 / -1" }}>
                            <label style={labelStyle}>Job Title *</label>
                            <input name="title" value={form.title} onChange={handleChange}
                                placeholder="e.g. Senior React Developer" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Department</label>
                            <input name="department" value={form.department} onChange={handleChange}
                                placeholder="e.g. Engineering" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Location</label>
                            <input name="location" value={form.location} onChange={handleChange}
                                placeholder="e.g. Remote, Mumbai" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Job Type</label>
                            <select name="jobType" value={form.jobType} onChange={handleChange} style={inputStyle}>
                                <option value="full-time">Full Time</option>
                                <option value="part-time">Part Time</option>
                                <option value="contract">Contract</option>
                                <option value="internship">Internship</option>
                            </select>
                        </div>
                        <div>
                            <label style={labelStyle}>Experience Required (years)</label>
                            <input type="number" name="experienceRequired" value={form.experienceRequired}
                                onChange={handleChange} min="0" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Application Deadline *</label>
                            <input type="date" name="deadline" value={form.deadline}
                                onChange={handleChange} style={inputStyle} />
                        </div>
                        <div style={{ gridColumn: "1 / -1" }}>
                            <label style={labelStyle}>Job Description *</label>
                            <textarea name="description" value={form.description} onChange={handleChange}
                                placeholder="Describe the role, responsibilities, and what you're looking for..."
                                rows={5} style={{ ...inputStyle, resize: "vertical" }} />
                        </div>
                    </div>
                </div>

                <div style={{ background: "white", borderRadius: "16px", padding: "32px", border: "1px solid #e2e8f0", marginBottom: "20px" }}>
                    <h2 style={{ fontSize: "16px", fontWeight: "700", color: "#0f172a", marginBottom: "8px" }}>
                        Skills & Requirements
                    </h2>
                    <p style={{ color: "#64748b", fontSize: "13px", marginBottom: "24px" }}>
                        Separate multiple skills with commas
                    </p>
                    <div style={{ display: "grid", gap: "20px" }}>
                        <div>
                            <label style={labelStyle}>Required Skills</label>
                            <input name="requirements" value={form.requirements} onChange={handleChange}
                                placeholder="React, Node.js, MongoDB, REST APIs" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Nice to Have</label>
                            <input name="niceToHave" value={form.niceToHave} onChange={handleChange}
                                placeholder="Docker, AWS, TypeScript" style={inputStyle} />
                        </div>
                    </div>
                </div>

                <div style={{ background: "white", borderRadius: "16px", padding: "32px", border: "1px solid #e2e8f0", marginBottom: "24px" }}>
                    <h2 style={{ fontSize: "16px", fontWeight: "700", color: "#0f172a", marginBottom: "24px" }}>
                        Salary Range
                    </h2>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "20px" }}>
                        <div>
                            <label style={labelStyle}>Minimum (₹)</label>
                            <input type="number" name="salaryMin" value={form.salary.min}
                                onChange={handleChange} placeholder="800000" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Maximum (₹)</label>
                            <input type="number" name="salaryMax" value={form.salary.max}
                                onChange={handleChange} placeholder="1500000" style={inputStyle} />
                        </div>
                        <div>
                            <label style={labelStyle}>Currency</label>
                            <select name="currency" value={form.salary.currency}
                                onChange={e => setForm({ ...form, salary: { ...form.salary, currency: e.target.value } })}
                                style={inputStyle}>
                                <option value="INR">INR</option>
                                <option value="USD">USD</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div style={{ display: "flex", gap: "12px" }}>
                    <button type="button" onClick={() => navigate("/jobs")} style={{
                        padding: "14px 28px", background: "white",
                        border: "1.5px solid #e2e8f0", borderRadius: "12px",
                        fontSize: "14px", fontWeight: "600", cursor: "pointer", color: "#64748b"
                    }}>Cancel</button>
                    <button type="submit" disabled={loading} style={{
                        padding: "14px 32px", background: loading ? "#a5b4fc" : "#6366f1",
                        color: "white", border: "none", borderRadius: "12px",
                        fontSize: "14px", fontWeight: "700", cursor: loading ? "not-allowed" : "pointer"
                    }}>
                        {loading ? "Creating..." : "Create Job Posting →"}
                    </button>
                </div>
            </form>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <label style={labelStyle}>Job Description *</label>
                <button type="button" onClick={handleGenerateDesc} disabled={generatingDesc} style={{
                    padding: "6px 14px", background: generatingDesc ? "#a5b4fc" : "#eef2ff",
                    color: "#6366f1", border: "none", borderRadius: "8px",
                    fontSize: "12px", fontWeight: "700", cursor: generatingDesc ? "not-allowed" : "pointer"
                }}>
                    {generatingDesc ? "Generating..." : "⚡ AI Generate"}
                </button>
            </div>
        </div>
    )
}

export default CreateJob